### ISSUE TITLE
/verify: If VC was not found in CSL then result must not be "verified"

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-service#106]
https://github.com/trustbloc/edge-service/blob/faed96ac75d91e6af42c910c4daca177eff49941/pkg/restapi/vc/operation/operations.go#L221

**Comment by fqutishat** [comment]
@llorllale I think the logic is correct if not found in the list it's mean valid

**Comment by fqutishat** [comment]
@sandrask ^^^

**Comment by llorllale** [comment]
Thanks @sandrask @fqutishat
