### ISSUE TITLE
Omit empty elements in issued credential

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#249]
currently we include `"credentialSchema": []` in our output but other implementation omit when empty.

**Comment by troyronda** [comment]
@kdimak @rolsonquadras @sudeshrshetty

**Comment by sudeshrshetty** [comment]
created https://github.com/hyperledger/aries-framework-go/issues/1627

**Comment by sudeshrshetty** [comment]
fix in aries: https://github.com/hyperledger/aries-framework-go/pull/1628
