### ISSUE TITLE
Replace issuer value in issued credential

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#251]
Interop samples:

**Current Result**
https://github.com/troyronda/w3c-vc-examples/blob/75a30da28370e302eed517b6b05f216a532386b4/test-suite/data/credential--issuer.sandbox.trustbloc.dev--CertifiedMillTestReport.json

**Input**
https://github.com/w3c-ccg/vc-examples/blob/5f4487141007d58785dff5cfee1e8a198e269a7b/docs/cmtr/examples/v0.2/cmtr-credential-v0.2.json

**Other Implementations**
- https://github.com/w3c-ccg/vc-examples/blob/d580be4a21967a0eeae72ebb1ac9dcee429609a9/test-suite/data/credential--api.neo-flow.com--CertifiedMillTestReport.json
- https://github.com/w3c-ccg/vc-examples/blob/master/test-suite/data/credential--api.neo-flow.com--CertifiedMillTestReport.json
- https://github.com/w3c-ccg/vc-examples/blob/master/test-suite/data/credential--issuer.interop.digitalbazaar.com--CertifiedMillTestReport.json
- https://github.com/w3c-ccg/vc-examples/blob/master/test-suite/data/credential--vc.transmute.world--CertifiedMillTestReport.json

**Comment by sudeshrshetty** [comment]
@troyronda @rolsonquadras @fqutishat 
Not sure if we should override ‘issuer’,  according to spec it can be anything, can also be jwk, but it should result to a document when dereferenced.
Here is the behavior of different vendor’s issue credential
DanubeTech: You can pass whatever as an issuer (valid URI) but dereferenced document will be used to create proofs. So they should have access to private key of DID you pass.
Digital Bazaar & Transmute: No matter what you pass, they gonna use hardcoded/predefined verification key, purpose, issuer DID etc. And issuer will be overridden in VC.
Our behaviour: You can pass whatever you want, we choose DID from profile to create proof. Issuer untouched.
So what should be our behaviour then??? Override whatever we get from credential request and override it from DID in profile??
Then we don’t need object type of issue credential (one with id & name)

**Comment by sudeshrshetty** [comment]
Here is the behaviour,

- profile will have new flag called `overwriteIssuer`

1. Issuer not provided : Use DID from profile as issuer
2. Issuer provided : 
      1. If profile.overWriteIssuer = true, override from profile
      2. If profile.overWriteIssuer = false, use issuer provided. If invalid URI then it should fail

Verification method: always should match Issuer set from above steps. If verification method doesn't match issuer then fail

@troyronda @rolsonquadras @fqutishat

**Comment by troyronda** [comment]
what’s the default verification method when the option is not provided? @sudeshrshetty

**Comment by sudeshrshetty** [comment]
existing logic : one from profile (first ed25519 key in key list)
