### ISSUE TITLE
did:key issuer profile

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#253]
It would be helpful to have an issuer profile that doesn't rely on the ledger, so we can demonstrate interop with those who don't support our DID method.

**Comment by rolsonquadras** [comment]
The BDD test for did:key are already available - https://github.com/trustbloc/edge-service/blob/9025e82d90e6eb50839ef205d4b5f7700168292e/test/bdd/features/thirdparty_verifier_e2e.feature#L20-L21.

Adding an new issuer to demo is tracked as part of https://github.com/trustbloc/edge-sandbox/issues/232.
