### ISSUE TITLE
Support holder mode and API

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#267]
https://transmute-industries.github.io/vc-http-api/#/Holder

- is configured based on profiles and is profile is selected based on path (similar to issuer).
- profile must be configured to allow usage as holder.
  - note: similarly, for issuance APIs, a profile must be configured to allow usage as an issuer.

**Comment by troyronda** [comment]
should also update BDD tests to use a Holder instance.

**Comment by rolsonquadras** [comment]
This has been implemented. Closing the issue.
