### ISSUE TITLE
Add BDD test with a did:key issuer

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#273]
Should have an additional case for a generic issuer/credential based on did:key

**Comment by sudeshrshetty** [comment]
Add a new entry [here](https://github.com/trustbloc/edge-service/blob/master/test/bdd/features/vc_e2e_api.feature#L30) using did:key
or
Add a new entry [here](https://github.com/trustbloc/edge-service/blob/master/test/bdd/features/thirdparty_verifier_e2e.feature#L18) with our verifier endpoint
