### ISSUE TITLE
Verifier mutation of the jws property

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#284]
1. Verifier must check for a Credential Signature Failure due to mutation of the jws property
          ✕ should pass with no mutation (969ms)
          ✓ should fail with with mutation (613ms)

    Expected: 200
    Received: 400

      171 |             };
      172 |             const res = await help.postJson(endpoint, body);
    > 173 |             expect(res.status).toBe(200);
          |                                ^
      174 |             expect(res.body.checks).toEqual(["proof"]);
      175 |           });
      176 |           it("should fail with with mutation", async () => {

**Comment by rolsonquadras** [comment]
This has been fixed as part of https://github.com/w3c-ccg/vc-examples/pull/49.
