### ISSUE TITLE
Configure plugfest test with at least 2 different DID methods as an issuer

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#285]
3.2 Issuer must support issuance of credentials with at least 2 different DID methods as an issuer
          ✕ meets criteria after all issuers have been tested (2ms)

----

        10. Verifier must be able to verify credentials with at least 2 different DID methods as the did issuer
          ✕ should pass (143ms)

**Comment by troyronda** [comment]
create issuer profile for each interop did:method. Leave `vc-issuer-interop` as did:trustbloc

e.g., vc-issuer-interop-v1, vc-issuer-interop-sov, vc-issuer-interop-key, ...

**Comment by troyronda** [comment]
- configure https://github.com/w3c-ccg/vc-examples/tree/master/plugfest-2020/vendors/trustbloc
- ensure above tests pass.

**Comment by rolsonquadras** [comment]
Need to update the test suite configuration after next deployment.

**Comment by rolsonquadras** [comment]
The second issuer has been pushed to W3C test suite. Here is the latest W3C interop report - https://w3c-ccg.github.io/vc-examples/plugfest-2020.html
