### ISSUE TITLE
Fix latest plugfest failures

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#327]
4. The Verifier’s Verify Credential HTTP API MUST fail to verify a Verifiable Credential with an added property to the credential.
      ✕ should fail (790ms)
7. The Verifier’s Verify Credential HTTP API MUST fail to verify a Verifiable Credential with an added property to the proof.
      ✕ should fail (851ms)
10. The Verifier’s Verify Credential HTTP API MUST verify a Verifiable Credential with at least 2 different DID methods set as the issuer property for a credential.
      ✕ should pass (719ms)
6. The Verifier’s Verify Presentation HTTP API MUST support “options.challenge” in the body of the POST request.
      ✕ should have error (669ms)

**Comment by rolsonquadras** [comment]
> 1. The Verifier’s Verify Credential HTTP API MUST fail to verify a Verifiable Credential with an added property to the credential.
>    ✕ should fail (790ms)
> 2. The Verifier’s Verify Credential HTTP API MUST fail to verify a Verifiable Credential with an added property to the proof.
>    ✕ should fail (851ms)

These are being worked as part of https://github.com/hyperledger/aries-framework-go/issues/1705 (cc: @kdimak )

> 3. The Verifier’s Verify Credential HTTP API MUST verify a Verifiable Credential with at least 2 different DID methods set as the issuer property for a credential.
>    ✕ should pass (719ms)

Fixed as part of https://github.com/w3c-ccg/vc-examples/pull/66.

> 4. The Verifier’s Verify Presentation HTTP API MUST support “options.challenge” in the body of the POST request.
>    ✕ should have error (669ms)

Fixed as part of https://github.com/trustbloc/edge-service/pull/315

**Comment by rolsonquadras** [comment]
Pending deployment in sandbox environment.

**Comment by rolsonquadras** [comment]
Changes have been deployed. All cases are passing now - https://w3c-ccg.github.io/vc-examples/plugfest-2020.html
