### ISSUE TITLE
Validate relationship between issuer, holder and verificationMethod

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-service#341]
> For non-ZKP proofs (e.g,. Ed25519Signature2018), the controller of the verificationMethod for the proof on the VC must match the issuer and the controller of the verificationMethod for the proof on the VP must match the holder, if holder is present.

> See the NOTE here for more information: https://www.w3.org/TR/vc-data-model/#proofs-signatures-0

**Comment by rolsonquadras** [comment]
https://github.com/w3c-ccg/vc-examples/issues/67#issuecomment-620187151
