### ISSUE TITLE
edge-service vs. specs vs. others

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-service#96]

**Comment by llorllale** [comment]
There are differences between all four actors (specs vs transmute vs digital bazaar vs edge-service).

There will be incoming PRs to the spec repo. [PR](https://github.com/w3c-ccg/vc-issuer-http-api/pull/18) submitted for the issuer API.

**Comment by llorllale** [comment]
# Aligning edge-service with vc-issuer-http-api

Spec version: [`5ccd7d96e9f3e52777e7c63c9253a4d8e47a4fe4`](https://github.com/w3c-ccg/vc-issuer-http-api/blob/5ccd7d96e9f3e52777e7c63c9253a4d8e47a4fe4/api.yml)

Spec note: there is consensus only on endpoint `/credentials/issueCredential`

## Summary

The 'shape' of the vc-issuer-http-api is now that of a 'signing API': the caller provides a fully-formed JSON-LD VC (minus proof) and optionally the URI of the signing key. The API lints the input VC, attaches the proof, and returns the VC-with-proof in the output. This differs from the edge-service API which has more of a "construct-and-sign" shape: it constructs the VC from disparate bits of input and attaches a proof section.

## Endpoints

* vc-issuer-http-api: `/credentials/issueCredential`
* edge-service: `/credential`

## Inputs

* vc-issuer-http-api:
  * `credential` object:
     * a fully formed JSON-LD VC (minus proof)
  * `options` object
     * `assertionMethod`: (optional) URI of the signing key. Eg. "did:web:example.com#z6MksHh7qHWvybLg5QTPPdG2DgEjjduBDArV9EF9mRiRzMBN"
* edge-service:
  * `@context`: array of contexts
  * `credentialSubject`: used as the [VC credentialSubject](https://www.w3.org/TR/vc-data-model/#credential-subject)
  * `issuer`: unused
  * `type`: used as the [VC type](https://www.w3.org/TR/vc-data-model/#types)
  * `profile`: used in a manner similar to the `assertionMethod` of the vc-issuer-http-api (see above)

## Outputs

* vc-issuer-http-api:
  * **unclear**: an object that contains the "issued credential" and that "SHOULD include a reference or ID that can be used later for other parts of the API"
* edge-service:
  * A JSON-LD VC with proof

**Comment by llorllale** [comment]
# Aligning edge-service with vc-verifier-http-api

> **TODO:** will add once basic agreement has been reached

**Comment by troyronda** [comment]
@rolsonquadras @llorllale 

I think this task is now documenting what we are doing... spec endpoints + our additional endpoints.

**Comment by rolsonquadras** [comment]
The APIs documentation is available at https://github.com/trustbloc/edge-service/blob/master/docs/vc-rest/README.md#rest-api-endpoints.
